---
## docker-compose supports runtime argument for v2 only currently.
version: '2.3'
services:
  pygpu_base:
    container_name: pygpu_base
    build:
      context: .
      dockerfile: docker/base.docker
    tty: true
    stdin_open: true
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0 # This is system dependent!
    command: ["bash"]
    image: prefrontalvortex/python_gpu_ml:base
  tf_pygpu:
    container_name: tf_pygpu
    build:
      context: .
      dockerfile: docker/tf.docker
    tty: true
    stdin_open: true
    runtime: nvidia
    environment:
    - CUDA_VISIBLE_DEVICES=0 # This is system dependent!
    command: ["bash"]
    image: prefrontalvortex/python_gpu_ml:tf_pygpu
  tf_stress_gpu:
    container_name: tf_stress_gpu
    build:
      context: .
      dockerfile: docker/tf_stress_gpu.docker
    tty: true
    stdin_open: true
    runtime: nvidia
    environment:
    - CUDA_VISIBLE_DEVICES=0 # This is system dependent!
    command: ["python3", "python_gpu_tools/python_gpu_tools/mnist.py"]
    image: prefrontalvortex/gpu-stress-tf:latest
  pytorch_stress_gpu:
    container_name: pytorch_stress_gpu
    build:
      context: .
      dockerfile: docker/pytorch_stress_gpu.docker
    tty: true
    stdin_open: true
    runtime: nvidia
    environment:
    - CUDA_VISIBLE_DEVICES=0 # This is system dependent!
    command: ["bash"]
    image: prefrontalvortex/gpu-stress-pytorch:latest
  data_pygpu_testsets:
    build:
      context: .
      dockerfile: docker/data_testsets.docker
    image: prefrontalvortex/data_pygpu_testsets:latest
...
